Models/LoanPlan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace LoanManagementSystem.Models
{
    public class LoanPlan
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Loan Plan in Month")]
        public int Month { get; set; }
        [Required]
        [DisplayName("Loan Interest")]
        public decimal Interest { get; set; }
        [Required]
        [DisplayName("Monthly Over Due Penalty")]
        public decimal MonthlyOverDuePenalty { get; set; }
    }
}

Controllers/administrator/AdministratorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using LoanManagementSystem.Helpers;

namespace LoanManagementSystem.Controllers.administrator
{
    public class AdministratorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Loan()
        {
            return View();
        }
        public IActionResult Payment()
        {
            return View();
        }
        public IActionResult LoanPlan()
        {
            ViewBag.LoanPlanActive = "active";
            return View();
        }
        public IActionResult LoanType()
        {
            return View();
        }
        public IActionResult Report()
        {
            return View();
        }
        public IActionResult Customers()
        {
            return View();
        }
        public IActionResult Users()
        {
            return View();
        }
        public RedirectToActionResult Logout()
        {
            HttpContext.Session.SetInt32("userId", -1);
            HttpContext.Session.SetInt32("isAdmin", -1);
            HttpContext.Session.SetString("username", "");
            SessionHelper.SetObjectAsJson(HttpContext.Session, "user", null);

            //Redirects to Index Action Method from HomeController
            return RedirectToAction(actionName: "Index", controllerName: "Home");


        }
    }
}

Views/LoanPlan/Index.cshtml
@model IEnumerable<LoanManagementSystem.Models.LoanPlan>

@{
    ViewData["Title"] = "Loan Plan";
    ViewBag.LoanPlanActive = "active";

}

<h1>Loan Plans</h1>

<p>
    <a asp-controller="Administrator" asp-action="LoanPlan">Add New Plan</a>
</p>
<table class="table table-responsive table-striped table-hover w-100 border-0">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Month)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Interest)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MonthlyOverDuePenalty)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Month)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Interest)&nbsp;%
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MonthlyOverDuePenalty)&nbsp;%
                </td>
                <td>
                    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" class="btn btn-info" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id"><i class="fa-solid fa-circle-trash"></i>Delete</a>
                </td>
            </tr>
        }
        <tr>
            <td colspan="4">
                Empty Database
            </td>

        </tr>
    </tbody>
</table>